name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - Dockerfile
      - requirements_dev.txt
      - "saleor/**"
      - ".github/workflows/pytest.yml"
  push:
    branches:
      - main
      - ci/*
    paths:
      - "**.py"
      - Dockerfile
      - requirements_dev.txt
      - "saleor/**"

env:
  BENCH_PATH: ./queries-results.json
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"
  SECRET_KEY: ci-test

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: apt-get install -y libpq-dev

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # sphinxcontrib-applehelp added due to https://github.com/coddingtonbear/python-measurement/issues/75.
      # To remove once the issue is resolved.
      - name: Install dependencies
        run: |
          python -m pip install sphinxcontrib-applehelp==1.0.2
          python -m pip install wheel
          python -m pip install -r requirements_dev.txt

      # Run linters and Django related checks
      - name: Run Linters and Checks
        run: |
          pre-commit run --all
        if: ${{ always() }}
